---
title: "mp3"
output: html_document
---


```{r}
library(tidyverse)
library(macleish)
library(sf)
```

```{r}
#reading downloaded 3m contour data from MassGIS 
contour_what <- st_read("~/Downloads/hp337/hp337.shp") 
contour_conway <-st_read("~/Downloads/hp68/hp68.shp")

#converting these two shapefiles to sf and changing projection to match macleish_layers
contour1 <- st_as_sf(contour_what) %>% 
  st_transform(contour_what, crs = 4326)
contour2 <- st_as_sf(contour_conway)  %>% 
  st_transform(contour_conway, crs = 4326)
class(contour1)
class(contour2)
```

```{r}
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["research"]], color = "red") %>%
  addCircleMarkers(data = macleish_layers[["challenge_courses"]], color = "red") %>%
  addPolylines(data = macleish_layers[["trails"]], color = "brown", weight = 1) %>%
  addPolylines(data = macleish_layers[["streams"]], color = "blue", weight = 1) %>%
  addPolygons(data = macleish_layers[["boundary"]], stroke = TRUE, color = "black", fill = NA, weight = 2, opacity = 2) %>%
  addPolygons(data = macleish_layers[["forests"]], color = "green", weight = 1, fill = NA) %>%
  addPolygons(data = macleish_layers[["wetlands"]], color = "blue", weight = 1) %>%
  addPolylines(data = contour1, color = "black", weight = 1) %>%
  addPolylines(data = contour2, color = "black", weight = 1) 
```

To-do
- ask about automatically zooming in more on the map
- write problem statement
- 500-800 word description w/ reccommendation
- include a short discussion on the resources necessary to implement your recommendation:
what will it cost?
how long will it take?
are there any concerns about environmental impact?
do you see any major roadblocks?

We used a github repository [^1]

```{r}
#joining datasets (doesn't work as of now... not necessary??)
full_contour <- inner_join(contour1, contour2, by = c("ELEV_FT" = "ELEV_FT"))
full_contour
```


[^1]: [Link to github repository](https://github.com/rmoskowitz/mp3)